package br.com.glb.entidades;
// Generated 11/04/2014 23:32:24 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Agencia generated by hbm2java
 */
@Entity
@Table(name = "agencia", schema = "public"
)
public class Agencia implements java.io.Serializable {

    private int id;
    private Banco banco;
    private Cidade cidade;
    private String digito;
    private String cep;
    private String logradouro;
    private String numero;
    private String descricao;
    private Integer usuario;
    private Set contas = new HashSet(0);

    public Agencia() {
    }

    public Agencia(int id, Banco banco, Cidade cidade, String digito, String cep, String logradouro, String numero, String descricao) {
        this.id = id;
        this.banco = banco;
        this.cidade = cidade;
        this.digito = digito;
        this.cep = cep;
        this.logradouro = logradouro;
        this.numero = numero;
        this.descricao = descricao;
    }

    public Agencia(int id, Banco banco, Cidade cidade, String digito, String cep, String logradouro, String numero, String descricao, Integer usuario, Set contas) {
        this.id = id;
        this.banco = banco;
        this.cidade = cidade;
        this.digito = digito;
        this.cep = cep;
        this.logradouro = logradouro;
        this.numero = numero;
        this.descricao = descricao;
        this.usuario = usuario;
        this.contas = contas;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "banco_id", nullable = false)
    public Banco getBanco() {
        return this.banco;
    }

    public void setBanco(Banco banco) {
        this.banco = banco;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cidade_id", nullable = false)
    public Cidade getCidade() {
        return this.cidade;
    }

    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    @Column(name = "digito", nullable = false)
    public String getDigito() {
        return this.digito;
    }

    public void setDigito(String digito) {
        this.digito = digito;
    }

    @Column(name = "cep", nullable = false)
    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    @Column(name = "logradouro", nullable = false)
    public String getLogradouro() {
        return this.logradouro;
    }

    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    @Column(name = "numero", nullable = false)
    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "agencia")
    public Set getContas() {
        return this.contas;
    }

    public void setContas(Set contas) {
        this.contas = contas;
    }

}
