package br.com.glb.entidades;
// Generated 11/04/2014 23:32:24 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Banco generated by hbm2java
 */
@Entity
@Table(name="banco"
    ,schema="public"
)
public class Banco  implements java.io.Serializable {


     private String cnpj;
     private String descricao;
     private Integer usuario;
     private Set agencias = new HashSet(0);

    public Banco() {
    }

	
    public Banco(String cnpj, String descricao) {
        this.cnpj = cnpj;
        this.descricao = descricao;
    }
    public Banco(String cnpj, String descricao, Integer usuario, Set agencias) {
       this.cnpj = cnpj;
       this.descricao = descricao;
       this.usuario = usuario;
       this.agencias = agencias;
    }
   
     @Id 

    
    @Column(name="cnpj", unique=true, nullable=false)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="descricao", nullable=false)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="usuario")
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="banco")
    public Set getAgencias() {
        return this.agencias;
    }
    
    public void setAgencias(Set agencias) {
        this.agencias = agencias;
    }




}


