package br.com.glb.entidades;
// Generated 11/04/2014 23:32:24 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContemAliquota generated by hbm2java
 */
@Entity
@Table(name="contem_aliquota"
    ,schema="public"
)
public class ContemAliquota  implements java.io.Serializable {


     private int id;
     private Aliquota aliquota;
     private Conta conta;
     private Integer usuario;

    public ContemAliquota() {
    }

	
    public ContemAliquota(int id, Aliquota aliquota, Conta conta) {
        this.id = id;
        this.aliquota = aliquota;
        this.conta = conta;
    }
    public ContemAliquota(int id, Aliquota aliquota, Conta conta, Integer usuario) {
       this.id = id;
       this.aliquota = aliquota;
       this.conta = conta;
       this.usuario = usuario;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="conta_id", nullable=false)
    public Aliquota getAliquota() {
        return this.aliquota;
    }
    
    public void setAliquota(Aliquota aliquota) {
        this.aliquota = aliquota;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aliquota_id", nullable=false)
    public Conta getConta() {
        return this.conta;
    }
    
    public void setConta(Conta conta) {
        this.conta = conta;
    }

    
    @Column(name="usuario")
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }




}


