package br.com.glb.entidades;
// Generated 11/04/2014 23:32:24 by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Fechamento generated by hbm2java
 */
@Entity
@Table(name="fechamento"
    ,schema="public"
)
public class Fechamento  implements java.io.Serializable {


     private FechamentoId id;
     private Conta conta;
     private Integer usuario;

    public Fechamento() {
    }

	
    public Fechamento(FechamentoId id, Conta conta) {
        this.id = id;
        this.conta = conta;
    }
    public Fechamento(FechamentoId id, Conta conta, Integer usuario) {
       this.id = id;
       this.conta = conta;
       this.usuario = usuario;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="dataInicio", column=@Column(name="data_inicio", nullable=false, length=13) ), 
        @AttributeOverride(name="dataFim", column=@Column(name="data_fim", nullable=false, length=13) ), 
        @AttributeOverride(name="contaId", column=@Column(name="conta_id", nullable=false) ) } )
    public FechamentoId getId() {
        return this.id;
    }
    
    public void setId(FechamentoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="conta_id", nullable=false, insertable=false, updatable=false)
    public Conta getConta() {
        return this.conta;
    }
    
    public void setConta(Conta conta) {
        this.conta = conta;
    }

    
    @Column(name="usuario")
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }




}


