package br.com.glb.entidades;
// Generated 11/04/2014 23:32:24 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FechamentoId generated by hbm2java
 */
@Embeddable
public class FechamentoId  implements java.io.Serializable {


     private Date dataInicio;
     private Date dataFim;
     private int contaId;

    public FechamentoId() {
    }

    public FechamentoId(Date dataInicio, Date dataFim, int contaId) {
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
       this.contaId = contaId;
    }
   


    @Column(name="data_inicio", nullable=false, length=13)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }


    @Column(name="data_fim", nullable=false, length=13)
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }


    @Column(name="conta_id", nullable=false)
    public int getContaId() {
        return this.contaId;
    }
    
    public void setContaId(int contaId) {
        this.contaId = contaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FechamentoId) ) return false;
		 FechamentoId castOther = ( FechamentoId ) other; 
         
		 return ( (this.getDataInicio()==castOther.getDataInicio()) || ( this.getDataInicio()!=null && castOther.getDataInicio()!=null && this.getDataInicio().equals(castOther.getDataInicio()) ) )
 && ( (this.getDataFim()==castOther.getDataFim()) || ( this.getDataFim()!=null && castOther.getDataFim()!=null && this.getDataFim().equals(castOther.getDataFim()) ) )
 && (this.getContaId()==castOther.getContaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDataInicio() == null ? 0 : this.getDataInicio().hashCode() );
         result = 37 * result + ( getDataFim() == null ? 0 : this.getDataFim().hashCode() );
         result = 37 * result + this.getContaId();
         return result;
   }   


}


