package br.com.glb.entidades;
// Generated 11/04/2014 23:32:24 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ficha generated by hbm2java
 */
@Entity
@Table(name = "ficha", schema = "public"
)
public class Ficha implements java.io.Serializable {

    private int numero;
    private Detalhamento detalhamento;
    private Rubrica rubrica;
    private Alinea alinea;
    private Especie especie;
    private Subalinea subalinea;
    private Origem origem;
    private CategoriaEconomica categoriaEconomica;
    private String descricao;
    private Integer usuario;
    private Set identificacaoAvisos = new HashSet(0);

    public Ficha() {
    }

    public Ficha(int numero, Detalhamento detalhamento, Rubrica rubrica, Alinea alinea, Especie especie, Subalinea subalinea, Origem origem, CategoriaEconomica categoriaEconomica, String descricao) {
        this.numero = numero;
        this.detalhamento = detalhamento;
        this.rubrica = rubrica;
        this.alinea = alinea;
        this.especie = especie;
        this.subalinea = subalinea;
        this.origem = origem;
        this.categoriaEconomica = categoriaEconomica;
        this.descricao = descricao;
    }

    public Ficha(int numero, Detalhamento detalhamento, Rubrica rubrica, Alinea alinea, Especie especie, Subalinea subalinea, Origem origem, CategoriaEconomica categoriaEconomica, String descricao, Integer usuario, Set identificacaoAvisos) {
        this.numero = numero;
        this.detalhamento = detalhamento;
        this.rubrica = rubrica;
        this.alinea = alinea;
        this.especie = especie;
        this.subalinea = subalinea;
        this.origem = origem;
        this.categoriaEconomica = categoriaEconomica;
        this.descricao = descricao;
        this.usuario = usuario;
        this.identificacaoAvisos = identificacaoAvisos;
    }

    @Id

    @Column(name = "numero", unique = true, nullable = false)
    public int getNumero() {
        return this.numero;
    }

    public void setNumero(int numero) {
        this.numero = numero;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "detalhamento", nullable = false)
    public Detalhamento getDetalhamento() {
        return this.detalhamento;
    }

    public void setDetalhamento(Detalhamento detalhamento) {
        this.detalhamento = detalhamento;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "rubrica", nullable = false)
    public Rubrica getRubrica() {
        return this.rubrica;
    }

    public void setRubrica(Rubrica rubrica) {
        this.rubrica = rubrica;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "alinea", nullable = false)
    public Alinea getAlinea() {
        return this.alinea;
    }

    public void setAlinea(Alinea alinea) {
        this.alinea = alinea;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "especie", nullable = false)
    public Especie getEspecie() {
        return this.especie;
    }

    public void setEspecie(Especie especie) {
        this.especie = especie;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subalinea", nullable = false)
    public Subalinea getSubalinea() {
        return this.subalinea;
    }

    public void setSubalinea(Subalinea subalinea) {
        this.subalinea = subalinea;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "origem", nullable = false)
    public Origem getOrigem() {
        return this.origem;
    }

    public void setOrigem(Origem origem) {
        this.origem = origem;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "categoria_economica", nullable = false)
    public CategoriaEconomica getCategoriaEconomica() {
        return this.categoriaEconomica;
    }

    public void setCategoriaEconomica(CategoriaEconomica categoriaEconomica) {
        this.categoriaEconomica = categoriaEconomica;
    }

    @Column(name = "descricao", nullable = false)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Column(name = "usuario")
    public Integer getUsuario() {
        return this.usuario;
    }

    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ficha")
    public Set getIdentificacaoAvisos() {
        return this.identificacaoAvisos;
    }

    public void setIdentificacaoAvisos(Set identificacaoAvisos) {
        this.identificacaoAvisos = identificacaoAvisos;
    }

}
