package br.com.glb.entidades;
// Generated 11/04/2014 23:32:24 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Permissao generated by hbm2java
 */
@Entity
@Table(name="permissao"
    ,schema="public"
)
public class Permissao  implements java.io.Serializable {


     private int id;
     private String permissao;
     private Integer usuario;
     private Set possuiPermissaos = new HashSet(0);

    public Permissao() {
    }

	
    public Permissao(int id, String permissao) {
        this.id = id;
        this.permissao = permissao;
    }
    public Permissao(int id, String permissao, Integer usuario, Set possuiPermissaos) {
       this.id = id;
       this.permissao = permissao;
       this.usuario = usuario;
       this.possuiPermissaos = possuiPermissaos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="permissao", nullable=false)
    public String getPermissao() {
        return this.permissao;
    }
    
    public void setPermissao(String permissao) {
        this.permissao = permissao;
    }

    
    @Column(name="usuario")
    public Integer getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Integer usuario) {
        this.usuario = usuario;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="permissao")
    public Set getPossuiPermissaos() {
        return this.possuiPermissaos;
    }
    
    public void setPossuiPermissaos(Set possuiPermissaos) {
        this.possuiPermissaos = possuiPermissaos;
    }




}


