package br.com.glb.entidades;
// Generated 11/04/2014 23:32:24 by Hibernate Tools 3.6.0


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PossuiPermissao generated by hbm2java
 */
@Entity
@Table(name="possui_permissao"
    ,schema="public"
)
public class PossuiPermissao  implements java.io.Serializable {


     private PossuiPermissaoId id;
     private Usuario usuario;
     private Permissao permissao;
     private Integer usuario_1;

    public PossuiPermissao() {
    }

	
    public PossuiPermissao(PossuiPermissaoId id, Usuario usuario, Permissao permissao) {
        this.id = id;
        this.usuario = usuario;
        this.permissao = permissao;
    }
    public PossuiPermissao(PossuiPermissaoId id, Usuario usuario, Permissao permissao, Integer usuario_1) {
       this.id = id;
       this.usuario = usuario;
       this.permissao = permissao;
       this.usuario_1 = usuario_1;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="usuarioId", column=@Column(name="usuario_id", nullable=false) ), 
        @AttributeOverride(name="permissaoId", column=@Column(name="permissao_id", nullable=false) ) } )
    public PossuiPermissaoId getId() {
        return this.id;
    }
    
    public void setId(PossuiPermissaoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_id", nullable=false, insertable=false, updatable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="permissao_id", nullable=false, insertable=false, updatable=false)
    public Permissao getPermissao() {
        return this.permissao;
    }
    
    public void setPermissao(Permissao permissao) {
        this.permissao = permissao;
    }

    
    @Column(name="usuario")
    public Integer getUsuario_1() {
        return this.usuario_1;
    }
    
    public void setUsuario_1(Integer usuario_1) {
        this.usuario_1 = usuario_1;
    }




}


