package br.com.glb.entidades;
// Generated 11/04/2014 23:32:24 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PossuiPermissaoId generated by hbm2java
 */
@Embeddable
public class PossuiPermissaoId  implements java.io.Serializable {


     private int usuarioId;
     private int permissaoId;

    public PossuiPermissaoId() {
    }

    public PossuiPermissaoId(int usuarioId, int permissaoId) {
       this.usuarioId = usuarioId;
       this.permissaoId = permissaoId;
    }
   


    @Column(name="usuario_id", nullable=false)
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }


    @Column(name="permissao_id", nullable=false)
    public int getPermissaoId() {
        return this.permissaoId;
    }
    
    public void setPermissaoId(int permissaoId) {
        this.permissaoId = permissaoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PossuiPermissaoId) ) return false;
		 PossuiPermissaoId castOther = ( PossuiPermissaoId ) other; 
         
		 return (this.getUsuarioId()==castOther.getUsuarioId())
 && (this.getPermissaoId()==castOther.getPermissaoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUsuarioId();
         result = 37 * result + this.getPermissaoId();
         return result;
   }   


}


